### ISSUE TITLE
[BUG] Fails to execute if the solution file contains a Dependency Validation project [.modelproj]

### ISSUE THREAD

**Issue by bjuraga** [mrlacey/DontCopyAlways#6]
I have a solution that contains a Dependency Validation project [.modelproj] and the extension fails to process the solution. Would be nice to add support for this project file especially because having this project adds several minutes to a build and i can see a lot of IO operations due to it.

Log:
  <entry>
    <record>3103</record>
    <time>2021/02/05 13:50:01.619</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [DontCopyAlwaysPackage]</description>
    <guid>{452EF2B4-1788-49A6-8F34-B65812B45E8D}</guid>
  </entry>
  <entry>
    <record>3104</record>
    <time>2021/02/05 13:50:01.623</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [DontCopyAlwaysPackage]Source: "mscorlib" Description: Could not find file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\DependencyValidation.modelproj".
System.IO.FileNotFoundException: Could not find file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\DependencyValidation.modelproj".
File name: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\DependencyValidation.modelproj"
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Threading.CompressedStack.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at DontCopyAlways.DontCopyAlwaysPackage.&lt;ReportOnProjectsAsync&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DontCopyAlways.DontCopyAlwaysPackage.&lt;CheckAllProjectsInSolutionAsync&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DontCopyAlways.DontCopyAlwaysPackage.&lt;InitializeAsync&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.UIThreadReentrancyScope.WaitOnTaskCompleteInternal(Task task, CancellationToken cancel, Int32 ms)
   at Microsoft.VisualStudio.Shell.UIThreadReentrancyScope.WaitOnTaskComplete(Task task, CancellationToken cancel, Int32 ms)
   at Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass100_1.&lt;InternalGetResult&gt;b__1()
   at Microsoft.VisualStudio.Services.VsTask.IgnoreObjectDisposedException(Action action)
   at Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass100_0.&lt;InternalGetResult&gt;b__0()
   at Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass108_0.&lt;InvokeWithWaitDialog&gt;b__0()
   at Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog[T](Func`1 function)
   at Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog(Action action)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
   at Microsoft.VisualStudio.Services.VsTask.GetResult()</description>
    <guid>{452EF2B4-1788-49A6-8F34-B65812B45E8D}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>3105</record>
    <time>2021/02/05 13:50:01.629</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [DontCopyAlwaysPackage]</description>
    <guid>{452EF2B4-1788-49A6-8F34-B65812B45E8D}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by mrlacey** [comment]
I've never heard of a "Dependency Validation project" but will take a look.

**Comment by bjuraga** [comment]
Workaround for this is to unload the Dependency Validation project. Thanks for this extension, Works great!

**Comment by mrlacey** [comment]
So, it seems there's some "unique behavior" (it might not be a bug--so I won't call it that) for the way Dependency Validation projects behave within Visual Studio. When asked for the absolute path to the project file, this project file just gives the project name and not the full path.
As the code was previously assuming that the value it got for the full path was a full path it was leading to an error by trying to load a file from a directory where it wasn't located (the working directory.)
Anyway, now I know and can account for this.
Expect the extension to cope with such project types in the next version.

**Comment by mrlacey** [comment]
This functionality has been incorporated into version 1.2 and is now available from the marketplace.

Please show your support and appreciation by leaving a rating/review: https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.DontCopyAlways&ssr=false#review-details

Thanks.
